// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TH_Server.TH_Packet
{

public enum EChat : sbyte
{
  World = 0,
  Channel = 1,
  General = 2,
  Whisper = 3,
};


}
