// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TH_Server.TH_Packet
{

public enum EServer : sbyte
{
  Server_1 = 0,
  Server_2 = 1,
  Server_END = 2,
};


}
