// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TH_Server.TH_Packet
{

public enum PacketData : byte
{
  NONE = 0,
  LOGIN = 1,
  SPAWN = 2,
  CHAT = 3,
  PLAYER = 4,
  MONSTER = 5,
};


}
