// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TH_Server.TH_Packet
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Packet : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Packet GetRootAsPacket(ByteBuffer _bb) { return GetRootAsPacket(_bb, new Packet()); }
  public static Packet GetRootAsPacket(ByteBuffer _bb, Packet obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Packet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public TH_Server.TH_Packet.PacketData DataType { get { int o = __p.__offset(4); return o != 0 ? (TH_Server.TH_Packet.PacketData)__p.bb.Get(o + __p.bb_pos) : TH_Server.TH_Packet.PacketData.NONE; } }
  public TTable? Data<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public TH_Server.TH_Packet.LOGIN_DATA DataAsLOGIN() { return Data<TH_Server.TH_Packet.LOGIN_DATA>().Value; }
  public TH_Server.TH_Packet.SPAWN_DATA DataAsSPAWN() { return Data<TH_Server.TH_Packet.SPAWN_DATA>().Value; }
  public TH_Server.TH_Packet.CHAT_DATA DataAsCHAT() { return Data<TH_Server.TH_Packet.CHAT_DATA>().Value; }
  public TH_Server.TH_Packet.PLAYER_DATA DataAsPLAYER() { return Data<TH_Server.TH_Packet.PLAYER_DATA>().Value; }
  public TH_Server.TH_Packet.MONSTER_DATA DataAsMONSTER() { return Data<TH_Server.TH_Packet.MONSTER_DATA>().Value; }

  public static Offset<TH_Server.TH_Packet.Packet> CreatePacket(FlatBufferBuilder builder,
      TH_Server.TH_Packet.PacketData data_type = TH_Server.TH_Packet.PacketData.NONE,
      int dataOffset = 0) {
    builder.StartTable(2);
    Packet.AddData(builder, dataOffset);
    Packet.AddDataType(builder, data_type);
    return Packet.EndPacket(builder);
  }

  public static void StartPacket(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddDataType(FlatBufferBuilder builder, TH_Server.TH_Packet.PacketData dataType) { builder.AddByte(0, (byte)dataType, 0); }
  public static void AddData(FlatBufferBuilder builder, int dataOffset) { builder.AddOffset(1, dataOffset, 0); }
  public static Offset<TH_Server.TH_Packet.Packet> EndPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<TH_Server.TH_Packet.Packet>(o);
  }
}


static public class PacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*DataType*/, 1 /*TH_Server.TH_Packet.PacketData*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Data*/, TH_Server.TH_Packet.PacketDataVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
