// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Packet.proto

#include "Packet.pb.h"
#include "Packet.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace TH_SERVER {

static const char* RPC_System_method_names[] = {
  "/TH_SERVER.RPC_System/RPC_Login",
};

std::unique_ptr< RPC_System::Stub> RPC_System::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RPC_System::Stub> stub(new RPC_System::Stub(channel, options));
  return stub;
}

RPC_System::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_RPC_Login_(RPC_System_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RPC_System::Stub::RPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::TH_SERVER::Login_Recv* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TH_SERVER::Login_Send, ::TH_SERVER::Login_Recv, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RPC_Login_, context, request, response);
}

void RPC_System::Stub::async::RPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send* request, ::TH_SERVER::Login_Recv* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TH_SERVER::Login_Send, ::TH_SERVER::Login_Recv, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RPC_Login_, context, request, response, std::move(f));
}

void RPC_System::Stub::async::RPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send* request, ::TH_SERVER::Login_Recv* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RPC_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TH_SERVER::Login_Recv>* RPC_System::Stub::PrepareAsyncRPC_LoginRaw(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TH_SERVER::Login_Recv, ::TH_SERVER::Login_Send, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RPC_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TH_SERVER::Login_Recv>* RPC_System::Stub::AsyncRPC_LoginRaw(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRPC_LoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

RPC_System::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RPC_System_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RPC_System::Service, ::TH_SERVER::Login_Send, ::TH_SERVER::Login_Recv, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RPC_System::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TH_SERVER::Login_Send* req,
             ::TH_SERVER::Login_Recv* resp) {
               return service->RPC_Login(ctx, req, resp);
             }, this)));
}

RPC_System::Service::~Service() {
}

::grpc::Status RPC_System::Service::RPC_Login(::grpc::ServerContext* context, const ::TH_SERVER::Login_Send* request, ::TH_SERVER::Login_Recv* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace TH_SERVER

