// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Packet.proto
#ifndef GRPC_Packet_2eproto__INCLUDED
#define GRPC_Packet_2eproto__INCLUDED

#include "Packet.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace TH_SERVER {

class RPC_System final {
 public:
  static constexpr char const* service_full_name() {
    return "TH_SERVER.RPC_System";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::TH_SERVER::Login_Recv* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TH_SERVER::Login_Recv>> AsyncRPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TH_SERVER::Login_Recv>>(AsyncRPC_LoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TH_SERVER::Login_Recv>> PrepareAsyncRPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::TH_SERVER::Login_Recv>>(PrepareAsyncRPC_LoginRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void RPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send* request, ::TH_SERVER::Login_Recv* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send* request, ::TH_SERVER::Login_Recv* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TH_SERVER::Login_Recv>* AsyncRPC_LoginRaw(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::TH_SERVER::Login_Recv>* PrepareAsyncRPC_LoginRaw(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status RPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::TH_SERVER::Login_Recv* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TH_SERVER::Login_Recv>> AsyncRPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TH_SERVER::Login_Recv>>(AsyncRPC_LoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TH_SERVER::Login_Recv>> PrepareAsyncRPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::TH_SERVER::Login_Recv>>(PrepareAsyncRPC_LoginRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void RPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send* request, ::TH_SERVER::Login_Recv* response, std::function<void(::grpc::Status)>) override;
      void RPC_Login(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send* request, ::TH_SERVER::Login_Recv* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::TH_SERVER::Login_Recv>* AsyncRPC_LoginRaw(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::TH_SERVER::Login_Recv>* PrepareAsyncRPC_LoginRaw(::grpc::ClientContext* context, const ::TH_SERVER::Login_Send& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RPC_Login_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RPC_Login(::grpc::ServerContext* context, const ::TH_SERVER::Login_Send* request, ::TH_SERVER::Login_Recv* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RPC_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RPC_Login() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RPC_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_Login(::grpc::ServerContext* /*context*/, const ::TH_SERVER::Login_Send* /*request*/, ::TH_SERVER::Login_Recv* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRPC_Login(::grpc::ServerContext* context, ::TH_SERVER::Login_Send* request, ::grpc::ServerAsyncResponseWriter< ::TH_SERVER::Login_Recv>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RPC_Login<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_RPC_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RPC_Login() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::TH_SERVER::Login_Send, ::TH_SERVER::Login_Recv>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::TH_SERVER::Login_Send* request, ::TH_SERVER::Login_Recv* response) { return this->RPC_Login(context, request, response); }));}
    void SetMessageAllocatorFor_RPC_Login(
        ::grpc::MessageAllocator< ::TH_SERVER::Login_Send, ::TH_SERVER::Login_Recv>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::TH_SERVER::Login_Send, ::TH_SERVER::Login_Recv>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RPC_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_Login(::grpc::ServerContext* /*context*/, const ::TH_SERVER::Login_Send* /*request*/, ::TH_SERVER::Login_Recv* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RPC_Login(
      ::grpc::CallbackServerContext* /*context*/, const ::TH_SERVER::Login_Send* /*request*/, ::TH_SERVER::Login_Recv* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_RPC_Login<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RPC_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RPC_Login() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RPC_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_Login(::grpc::ServerContext* /*context*/, const ::TH_SERVER::Login_Send* /*request*/, ::TH_SERVER::Login_Recv* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RPC_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RPC_Login() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RPC_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_Login(::grpc::ServerContext* /*context*/, const ::TH_SERVER::Login_Send* /*request*/, ::TH_SERVER::Login_Recv* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRPC_Login(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RPC_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RPC_Login() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RPC_Login(context, request, response); }));
    }
    ~WithRawCallbackMethod_RPC_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RPC_Login(::grpc::ServerContext* /*context*/, const ::TH_SERVER::Login_Send* /*request*/, ::TH_SERVER::Login_Recv* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RPC_Login(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RPC_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RPC_Login() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::TH_SERVER::Login_Send, ::TH_SERVER::Login_Recv>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::TH_SERVER::Login_Send, ::TH_SERVER::Login_Recv>* streamer) {
                       return this->StreamedRPC_Login(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RPC_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RPC_Login(::grpc::ServerContext* /*context*/, const ::TH_SERVER::Login_Send* /*request*/, ::TH_SERVER::Login_Recv* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRPC_Login(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::TH_SERVER::Login_Send,::TH_SERVER::Login_Recv>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RPC_Login<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RPC_Login<Service > StreamedService;
};

}  // namespace TH_SERVER


#endif  // GRPC_Packet_2eproto__INCLUDED
